// Memory Vault Studio - Theme Registry (13+ Themes)

export const THEME_PRESETS = {
  friendship: {
    id: 'friendship',
    name: 'Friendship Scrapbook',
    bg: '#FAF6EE',
    primary: '#F8D48E',
    secondary: '#FFF7E8',
    accent: '#A2D2A9',
    text: '#2C1A0E',
    border: '#2C1A0E',
    fontFamily: '"Caveat", "Dancing Script", cursive, Georgia, serif',
    particles: 'sparkles',
    soundPreset: 'warm-acoustic',
    tapeStyle: 'stripe-yellow',
    icon: '🤝'
  },
  love: {
    id: 'love',
    name: 'Romantic Love',
    bg: '#FFF0F3',
    primary: '#FF758F',
    secondary: '#FFCCD5',
    accent: '#C9184A',
    text: '#590D22',
    border: '#800F2F',
    fontFamily: '"Dancing Script", cursive, Georgia, serif',
    particles: 'hearts',
    soundPreset: 'soft-romantic',
    tapeStyle: 'heart-pattern',
    icon: '💖'
  },
  birthday: {
    id: 'birthday',
    name: 'Birthday Party',
    bg: '#F0F7FF',
    primary: '#4D96FF',
    secondary: '#FFD93D',
    accent: '#FF6B6B',
    text: '#1E293B',
    border: '#0F172A',
    fontFamily: '"Outfit", sans-serif',
    particles: 'confetti',
    soundPreset: 'upbeat-pop',
    tapeStyle: 'confetti-pattern',
    icon: '🎉'
  },
  proposal: {
    id: 'proposal',
    name: 'Midnight Proposal',
    bg: '#0F172A',
    primary: '#F59E0B',
    secondary: '#1E293B',
    accent: '#EC4899',
    text: '#F8FAFC',
    border: '#F59E0B',
    fontFamily: '"Cinzel", "Playfair Display", serif',
    particles: 'fireflies',
    soundPreset: 'orchestral-dream',
    tapeStyle: 'gold-foil',
    icon: '💍'
  },
  wedding: {
    id: 'wedding',
    name: 'Golden Wedding',
    bg: '#FCFBF7',
    primary: '#D4AF37',
    secondary: '#F4E8C1',
    accent: '#8B0000',
    text: '#332C1E',
    border: '#D4AF37',
    fontFamily: '"Great Vibes", cursive, serif',
    particles: 'petals',
    soundPreset: 'classical-waltz',
    tapeStyle: 'lace-pattern',
    icon: '👰'
  },
  anniversary: {
    id: 'anniversary',
    name: 'Vintage Anniversary',
    bg: '#F5EBE0',
    primary: '#DDBEA9',
    secondary: '#FFE8D6',
    accent: '#CB997E',
    text: '#4A3E3D',
    border: '#6B5B52',
    fontFamily: '"Playfair Display", serif',
    particles: 'dust',
    soundPreset: 'vintage-vinyl',
    tapeStyle: 'kraft-tape',
    icon: '🥂'
  },
  baby: {
    id: 'baby',
    name: 'Baby Cloud',
    bg: '#F0F9FF',
    primary: '#BAE6FD',
    secondary: '#FDE68A',
    accent: '#F472B6',
    text: '#1E3A8A',
    border: '#3B82F6',
    fontFamily: '"Comic Neue", cursive, sans-serif',
    particles: 'butterflies',
    soundPreset: 'lullaby-box',
    tapeStyle: 'pastel-dots',
    icon: '👶'
  },
  graduation: {
    id: 'graduation',
    name: 'Graduation Day',
    bg: '#F8FAFC',
    primary: '#1E40AF',
    secondary: '#FEF08A',
    accent: '#DC2626',
    text: '#0F172A',
    border: '#1E3A8A',
    fontFamily: '"Inter", sans-serif',
    particles: 'confetti',
    soundPreset: 'fanfare-triumph',
    tapeStyle: 'navy-stripe',
    icon: '🎓'
  },
  christmas: {
    id: 'christmas',
    name: 'Cozy Christmas',
    bg: '#1A2E1A',
    primary: '#EF4444',
    secondary: '#166534',
    accent: '#F59E0B',
    text: '#F8FAFC',
    border: '#F59E0B',
    fontFamily: '"Mountains of Christmas", cursive',
    particles: 'snow',
    soundPreset: 'jingle-chimes',
    tapeStyle: 'holly-pattern',
    icon: '🎄'
  },
  diwali: {
    id: 'diwali',
    name: 'Diwali Lights',
    bg: '#2A0845',
    primary: '#FFD700',
    secondary: '#642B73',
    accent: '#FF4E50',
    text: '#FFF8DC',
    border: '#FFD700',
    fontFamily: '"Rozha One", serif',
    particles: 'diwali-lights',
    soundPreset: 'sitar-ambient',
    tapeStyle: 'gold-marigold',
    icon: '🪔'
  },
  raksha: {
    id: 'raksha',
    name: 'Raksha Bandhan',
    bg: '#FFFBEB',
    primary: '#F59E0B',
    secondary: '#FEF3C7',
    accent: '#E11D48',
    text: '#78350F',
    border: '#92400E',
    fontFamily: '"Kalam", cursive',
    particles: 'sparkles',
    soundPreset: 'festive-flute',
    tapeStyle: 'red-yellow-thread',
    icon: '🪡'
  },
  mothersDay: {
    id: 'mothersDay',
    name: "Mother's Day Blossom",
    bg: '#FDF2F8',
    primary: '#F472B6',
    secondary: '#FCE7F3',
    accent: '#DB2777',
    text: '#831843',
    border: '#9D174D',
    fontFamily: '"Sacramento", cursive',
    particles: 'petals',
    soundPreset: 'gentle-piano',
    tapeStyle: 'floral-pink',
    icon: '💐'
  },
  fathersDay: {
    id: 'fathersDay',
    name: "Father's Day Vintage",
    bg: '#ECFDF5',
    primary: '#059669',
    secondary: '#D1FAE5',
    accent: '#D97706',
    text: '#064E3B',
    border: '#047857',
    fontFamily: '"Merriweather", serif',
    particles: 'dust',
    soundPreset: 'warm-brass',
    tapeStyle: 'leather-texture',
    icon: '👔'
  },
  custom: {
    id: 'custom',
    name: 'Custom Theme',
    bg: '#FAF6EE',
    primary: '#F8D48E',
    secondary: '#FFF7E8',
    accent: '#A2D2A9',
    text: '#2C1A0E',
    border: '#2C1A0E',
    fontFamily: 'sans-serif',
    particles: 'sparkles',
    soundPreset: 'default',
    tapeStyle: 'plain-tape',
    icon: '🎨'
  }
};

export const getTheme = (themeKey) => {
  return THEME_PRESETS[themeKey] || THEME_PRESETS.friendship;
};
